# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
---
- name: Create Crow client config (JSON format)
  template:
    src: client.config.j2
    dest: "{{ graphql_dir }}/service/tools/config/interface/client.config"
    force: yes

- name: Create Crow server config (JSON format)
  template:
    src: server_config.config.j2
    dest: "{{ graphql_dir }}/service/http_server/server_config.config"
    force: yes

- name: Create systemd service for Crow HTTP Server
  template:
    src: crow_service.service.j2
    dest: /etc/systemd/system/crow-http.service
    force: yes
  notify:
    - reload systemd
    - restart crow

- name: Enable and restart Crow HTTP service
  systemd:
    name: crow-http
    state: restarted
    enabled: yes
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes